//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTWebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCustAccountMaster
    {
        public int ID { get; set; }
        public string ClientCustCode { get; set; }
        public string AccountId { get; set; }
        public string AccountName { get; set; }
        public string CustomerUniqueId { get; set; }
        public string PickupCode { get; set; }
        public string StoreCode { get; set; }
        public string HierarchyCode { get; set; }
        public string DivisionCode { get; set; }
        public string SubDivisionCode { get; set; }
        public string SubCode { get; set; }
        public string CustomerDeptCode { get; set; }
        public Nullable<decimal> CashLimit { get; set; }
        public string ClientCode { get; set; }
        public Nullable<bool> CancelFlag { get; set; }
        public string OtherDetail1 { get; set; }
        public string OtherDetail2 { get; set; }
        public string OtherDetail3 { get; set; }
        public string OtherDetail4 { get; set; }
        public string OtherDetail5 { get; set; }
        public string OtherDetail6 { get; set; }
        public string OtherDetail7 { get; set; }
        public string OtherDetail8 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ClientCustMaster ClientCustMaster { get; set; }
    }
}
