//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTWebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccountMaster
    {
        public string ClientCode { get; set; }
        public string AccountId { get; set; }
        public string AccountName { get; set; }
        public string RefName { get; set; }
        public string CustomerUniqueId { get; set; }
        public Nullable<bool> CancelFlag { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CompanyCode { get; set; }
    }
}
