//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTWebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCustMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientCustMaster()
        {
            this.ClientCustAccountMasters = new HashSet<ClientCustAccountMaster>();
        }
    
        public int ID { get; set; }
        public string ClientCustCode { get; set; }
        public string OldReferenceCode { get; set; }
        public string ClientCustName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> LOIStartDate { get; set; }
        public string AccountType { get; set; }
        public string DepartmentID { get; set; }
        public string Regioncode { get; set; }
        public string LocationCode { get; set; }
        public string HubLocationCode { get; set; }
        public string SubLocationCode { get; set; }
        public string CityCode { get; set; }
        public string CustomerBranchCode { get; set; }
        public string AreaCode { get; set; }
        public string CustomerCode { get; set; }
        public string PickPointCode { get; set; }
        public string CityLimitType { get; set; }
        public Nullable<int> FarBCLkm { get; set; }
        public Nullable<bool> MatchRequestAmount { get; set; }
        public Nullable<bool> SpecailDeal { get; set; }
        public Nullable<bool> PutOnHold { get; set; }
        public Nullable<bool> CancelFlag { get; set; }
        public string Remarks { get; set; }
        public string CompanyCode { get; set; }
        public string ClientNameAsPerLOI { get; set; }
        public string PickupStatus { get; set; }
        public string SolId { get; set; }
        public string LandMark { get; set; }
        public Nullable<decimal> MaxCashLimit { get; set; }
        public string AuthStatus { get; set; }
        public string RejectRemarks { get; set; }
        public string RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> CMSCashLimit { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string BusinessCityCode { get; set; }
        public string BaseCityCode { get; set; }
        public string NewZoneCode { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string AuthorizedBy { get; set; }
        public Nullable<bool> flagScanAmount { get; set; }
    
        public virtual SubLocationMast SubLocationMast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCustAccountMaster> ClientCustAccountMasters { get; set; }
        public virtual ClientCustBankDetail ClientCustBankDetail { get; set; }
    }
}
