//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTWebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCustBankDetail
    {
        public int ID { get; set; }
        public string ClientCustCode { get; set; }
        public string BusinessBank { get; set; }
        public string BillingBank { get; set; }
        public string DepositionBank { get; set; }
        public string DepositionType { get; set; }
        public string BusinessBankAddress { get; set; }
        public string BillingBankAddress { get; set; }
        public string DepositionBankAddress { get; set; }
        public string BusinessBankSolid { get; set; }
        public string BillingBankSolid { get; set; }
        public string DepositionBankSolid { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CDPPullingARG { get; set; }
        public string CompanyCode { get; set; }
    
        public virtual ClientCustMaster ClientCustMaster { get; set; }
    }
}
