//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTWebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public int ID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Nationality { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public string Telno { get; set; }
        public string Mobileno { get; set; }
        public string Faxno { get; set; }
        public string EmailId { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> VaultLimit { get; set; }
        public string CustomerRemarks { get; set; }
        public int IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CustType { get; set; }
        public Nullable<System.DateTime> AuthorizeDate { get; set; }
        public string RejectRemarks { get; set; }
        public string RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public string CustAuthStatus { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> ImageMapperID { get; set; }
        public int Priority_Id { get; set; }
        public Nullable<System.TimeSpan> BankClosureTime { get; set; }
    }
}
