//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTWebApi.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rcmentities : DbContext
    {
        public rcmentities()
            : base("name=rcmentities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientCustMaster> ClientCustMasters { get; set; }
        public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }
        public virtual DbSet<HublocationMast> HublocationMasts { get; set; }
        public virtual DbSet<LocationMast> LocationMasts { get; set; }
        public virtual DbSet<RegionMast> RegionMasts { get; set; }
        public virtual DbSet<SubLocationMast> SubLocationMasts { get; set; }
        public virtual DbSet<ClientCustAccountMaster> ClientCustAccountMasters { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<ClientAccountMaster> ClientAccountMasters { get; set; }
        public virtual DbSet<ClientCustBankDetail> ClientCustBankDetails { get; set; }
    }
}
