//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTWebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubLocationMast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubLocationMast()
        {
            this.ClientCustMasters = new HashSet<ClientCustMaster>();
        }
    
        public int id { get; set; }
        public string sublocationname { get; set; }
        public string sublocationcode { get; set; }
        public string hublocationcode { get; set; }
        public string CompanyCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCustMaster> ClientCustMasters { get; set; }
        public virtual HublocationMast HublocationMast { get; set; }
    }
}
