//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTWebApi.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public string BatchID { get; set; }
        public string TicketID { get; set; }
        public System.DateTime ticketdate { get; set; }
        public System.TimeSpan tikcettime { get; set; }
        public string tikcettype { get; set; }
        public string assignedto { get; set; }
        public string acceptstatus { get; set; }
        public Nullable<System.DateTime> resolveddate { get; set; }
        public string customer { get; set; }
        public string pickupcode { get; set; }
        public string clientcode { get; set; }
        public string crnno { get; set; }
        public string client { get; set; }
        public string area { get; set; }
        public string cdpncm { get; set; }
        public string region { get; set; }
        public string location { get; set; }
        public string hublocation { get; set; }
        public string problem { get; set; }
        public string mistakedoneby { get; set; }
        public string errortype { get; set; }
        public string querystatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string customertype { get; set; }
        public string hierarchycode { get; set; }
        public string filepath { get; set; }
        public string filename { get; set; }
        public string rejectremark { get; set; }
        public string Company { get; set; }
    }
}
